### ISSUE TITLE
Similar active projects

### ISSUE THREAD

**Issue by SK0P3iN** [ghostiam/vue-blocks#29]
Hi,
I find this project interesting, and I could really use it for an academic project I am working on.

Since it is abandoned, anyone know of any similar active projects that allow these interactions?

Thanks for your attention!

**Comment by ghostiam** [comment]
Hi. Thank you for your interest in the project.

These projects look good:
https://github.com/jagenjo/litegraph.js
https://github.com/newcat/baklavajs
https://www.totaljs.com/flow/

**Comment by SK0P3iN** [comment]
Thank you very much.

Best regards,
Juan Silva
